[package]
authors = ["Dario GÃ¶tz <dario.goetz@googlemail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
name = "keyboard_layout"
rust-version = "1.60"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.12"
smallmap = "1.4.2"
anyhow = "1.0.100"
colored = "2.0.2"
handlebars = "4.5.0"
log = "0.4.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.21"
thiserror = "1.0"
